name: Gradle Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: gradle-build-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ github.token }}
  NEXUS_USER: ${{ secrets.NEXUS_USER }}
  NEXUS_PASS: ${{ secrets.NEXUS_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for head
        run: git symbolic-ref -q HEAD || git rev-parse HEAD

      - name: Inspect
        run: |
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF: $GITHUB_REF"

#      - name: Setup Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: 17
#
#      - name: Build
#        uses: gradle/actions/setup-gradle@v4
#        with:
#          cache-read-only: ${{ github.ref_name != 'main' }}
#          cache-cleanup: on-success
#          gradle-home-cache-includes: |
#            caches
#            notifications
#            jdks
#            wrapper
#
#      - name: Gradle Check
#        run: ./gradlew build -s -x test -x functionalTest --parallel --build-cache
